# Immuni CircleCI configuration.
# Copyright (C) 2020 Presidenza del Consiglio dei Ministri.
# Please refer to the AUTHORS file for more information.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:281.0.0
    environment:
      - GOOGLE_PROJECT_ID: immuni-website-staging-42
      - COMPONENT: website
      - INSTANCE_GROUP: website
      - ZONE: us-central1-a
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: '[gcp] Authenticate with GCP'
          command: |
            echo "${GCP_DEPLOY_SERVICE_ACCOUNT_BASE64}" | base64 -d > /tmp/.service-account-key.json
            gcloud auth activate-service-account --key-file /tmp/.service-account-key.json
      - checkout:
          name: '[gcp] Checkout the code'
      - run:
          name: '[gcp] Configure docker with GCP'
          command: gcloud auth configure-docker
      - run:
          name: '[gcp] Build docker image'
          command: |
            docker build --build-arg HTPASSWD --tag "gcr.io/${GOOGLE_PROJECT_ID}/${COMPONENT}:${CIRCLE_SHA1}" .
      - run:
          name: '[gcp] Push docker image'
          command: docker push "gcr.io/${GOOGLE_PROJECT_ID}/${COMPONENT}:${CIRCLE_SHA1}"
      - run:
          name: '[gcp] Authenticate with GCP'
          command: |
            echo "${GCP_DEPLOY_SERVICE_ACCOUNT_BASE64}" | base64 -d > /tmp/.service-account-key.json
            gcloud auth activate-service-account --key-file /tmp/.service-account-key.json
      - run:
          name: '[gcp] Add a tag to the image being deployed'
          command: |
            export IMAGE_TO_DEPLOY="gcr.io/${GOOGLE_PROJECT_ID}/${COMPONENT}"
            gcloud container images add-tag "${IMAGE_TO_DEPLOY}:${CIRCLE_SHA1}" "${IMAGE_TO_DEPLOY}:latest"
      - run:
          command: gcloud compute instance-groups managed rolling-action replace ${INSTANCE_GROUP} --max-unavailable=0 --project="${GOOGLE_PROJECT_ID}" --zone="${ZONE}"
workflows:
  version: 2
  release:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
